### ISSUE TITLE
Some setting causes all new comments to be headers

### ISSUE THREAD

**Issue by snow-creature** [fpwong/AutoSizeComments#19] opened 2022-06-19 19:13 UTC
I had changed a bunch of settings in the "Editor Preferences" window. I realized after that only header comments are made when I press "C" in a graph regardless of what or if I have anything selected. 

After changing pretty much every setting, it seems the cause is the "Header Style" color being white or {1, 1, 1, 1}. Changing any value in the color to anything besides 1 (even anything above 1) makes comment nodes work as expected and will cause nodes using the header style in open graphs to expand. Setting it back to white makes new comment only into headers again and shrinks node using the header style. No other setting seemed to affect it.

This is a copy of my settings export converted to .txt since github doesn't accept .ini files : 
[Auto Size Comments Backup 2022-06-19 143448.txt](https://github.com/fpwong/AutoSizeComments/files/8936151/Auto.Size.Comments.Backup.2022-06-19.143448.txt)

**Comment by fpwong** [comment] 2022-06-20 02:37
Hi @snow-creature. This is not a bug but rather an issue in the way I've coded the headers. Whether or not a node is a header is determined by what colour it is. So if you set it to white then all new comment nodes will turn into header comments since they start off as white.

I initially coded it like this since I didn't want to externally store extra information about a node. But looking at it now, I could just store this info as a json. Will try to implement this soon.

As you said, I suggest you temporarily fix this by changing the colour to something very close to white.

**Comment by fpwong** [comment] 2022-07-07 01:57
Hi @snow-creature, this has been fixed in v3.1.0, you can download the [release here](https://github.com/fpwong/AutoSizeComments/releases/tag/v3.1.0-beta)

Otherwise I will update the marketplace version in a week or so

**Closed** 2022-07-07 02:00 UTC
